version: '3.2'

services:
  #For software development use with google oauth defined
  dev-app:
    build:
      context: .
      dockerfile: Dockerfile_Dev
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      ROOT_URL: ${APP_ROOT_URL:-http://localhost}
      MONGO_URL: mongodb://mongo:27017/meteor
      METEOR_SETTINGS: "${METEOR_SETTINGS}"
    command: /bin/bash meteor

  #For use by users interested in testing their tdfs/stims and not development
  test-app:
    build:
      context: .
      dockerfile: Dockerfile_Dev
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      ROOT_URL: ${APP_ROOT_URL:-http://localhost}
      MONGO_URL: mongodb://mongo:27017/meteor
      PORT: 3000

  #For use in production
  prod-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      ROOT_URL: ${APP_ROOT_URL:-http://localhost}
      MONGO_URL: mongodb://mongo:27017/meteor
    restart: unless-stopped

  mongo:
    image: mongo:3.2
    command:
      - --storageEngine=wiredTiger
    volumes:
     - ./data:/data/db
